# Generated by Django 5.2.17 on 2026-09-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(default='proyectos/logo.png', upload_to='proyectos/'),
        ),
    ]
